### ISSUE TITLE
Problem with Kernel 6.1.39

### ISSUE THREAD

**Issue by Stanislav-Lapata** [ivanovborislav/rtl8821au#3]
Hi I got error when try to install drivers on NixOS

```
/build/source/os_dep/linux/wifi_regd.c: In function 'rtw_regd_init':
/build/source/os_dep/linux/wifi_regd.c:409:36: error: 'REGULATORY_IGNORE_STALE_KICKOFF' undeclared (first use in this function)
  409 |         wiphy->regulatory_flags |= REGULATORY_IGNORE_STALE_KICKOFF;
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I think I have found something close
https://github.com/morrownr/88x2bu-20210702/issues/165

**Comment by fAntel** [comment]
Hi. I've encountered the same error recently when updated Xubuntu to 23.10 and got kernel version 6.5.0-10-generic with the update.
Fix from https://github.com/morrownr/88x2bu-20210702/issues/165#issuecomment-1730133899 works for me.
